#!/bin/sh
#


umask 0377
mkdir -p /root/.s3ql
cat << !! > /root/.s3ql/authinfo2 
[${S3QL_TYPE}] 
storage-url: ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
backend-login: ${S3QL_LOGIN}
backend-password: ${S3QL_PASSWD}
fs-passphrase: ${S3QL_FSPASSWD}
!!

mkdir -p ${S3QL_MOUNT_POINT}
fsck.s3ql ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
signal=$?

if [ $signal -eq 18 ] ; then
        echo "filestem not in use"
        mkfs.s3ql --plain -L $S3QL_STORAGE_CONTAINER --max-obj-size 10240 ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
elif [ $signal -ne 0 ] ; then
        echo "not safe to mount"
        exit 1
fi
mount.s3ql --log /root/.s3ql/mount.log --allow-other --compress zlib ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/ ${S3QL_MOUNT_POINT}
